### ISSUE TITLE
Search error when using **

### ISSUE THREAD

**Issue by ImTheDeveloper** [node-red/node-red-admin#3]
Messing around with the search and I tried the "likes" which resulted in an error. Unsure whether current search does this already? Probably worth just notifying the user if it does or doesnt when they try and do *

```
munkee@munkee-desktop:~$ node-red-admin search *schedule*
/usr/local/lib/node_modules/node-red-admin/lib/commands/search.js:38
                var filter = new RegExp(module);
                             ^
SyntaxError: Invalid regular expression: /*schedule*/: Nothing to repeat
    at new RegExp (native)
    at Request._callback (/usr/local/lib/node_modules/node-red-admin/lib/commands/search.js:38:30)
    at Request.self.callback (/usr/local/lib/node_modules/node-red-admin/node_modules/request/request.js:236:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-red-admin/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/node-red-admin/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:907:16
    at process._tickCallback (node.js:372:11)
```

**Comment by biancode** [comment]
likes is without * like:

`node-red-admin search tele`

`node-red-admin search teleg`

`node-red-admin search telegram`

`node-red-admin search node-red-contrib`

It could get closed state.
