### ISSUE TITLE
Installation error due to failed bcrypt build

### ISSUE THREAD

**Issue by E3V3A** [node-red/node-red-admin#5]
I'm using node **v6.5.0** with:
```bash
node-gyp@3.4.0
node-red@0.14.6
node-red-admin@0.1.2
node-red-contrib-bcrypt@0.0.47
npm@3.10.3
```

Because of below errors I installed the bcrypt 

The installation errors out when trying to build the `node-red-contrib-bcrypt` module, which worked fine, But even then the installation of ` node-red-admin` gives:

```
$ sudo npm install -g node-red-admin

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/node-red-admin -> /usr/local/lib/node_modules/node-red-admin/node-red-admin.js

> bcrypt@0.8.5 install /usr/local/lib/node_modules/node-red-admin/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/node-red-admin/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:0:
../../nan/nan.h:592:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:592:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:593:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:598:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:598:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:603:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:603:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:604:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:609:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:609:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
bcrypt_lib.target.mk:90: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/node-red-admin/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red-admin/node_modules/bcrypt
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:bcrypt@0.8.5 bcrypt@0.8.5 install: `node-gyp rebuild`
npm WARN install:bcrypt@0.8.5 Exit status 1
/usr/local/lib
└─┬ node-red-admin@0.1.2 
  ├── bcryptjs@2.3.0 
...
```

What could be the problem?

**Comment by dceejay** [comment]
the version of bcrypt in node-red-admin is slightly back level (0.8.5 vs latest 0.8.7) - we will bump version in package.

**Comment by knolleary** [comment]
node-red-admin@0.1.3 published to npm

**Comment by E3V3A** [comment]
Wow! I really appreciate how fast you respond.  Thanks guys.

**Comment by dceejay** [comment]
Thank you for spotting the bug !
